version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: pg_db
    depends_on:
      - pg_admin

  pgadmin:
    image: dpage/pgadmin4:6
    environment: 
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: yourpasswd
    container_name: pg_admin
    ports:
      - "80:80"
